name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ "17", "19", "20" ]

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: gradle

    - name: create properties
      run: |
        touch android/properties/private-github.properties
        touch android/properties/private-playstore.properties

    - name: grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleFdroidDebug assemblePlaystoreDebug assembleGithubDebug --no-daemon

    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: MozStumbler-fdroid-debug-${{ matrix.java }}-${{ github.sha }}.apk
        path: android/build/outputs/apk/fdroid/debug/MozStumbler-fdroid-debug.apk
